# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import logquery_pb2 as logquery__pb2


class LogQueryStub(object):
    """The logquery service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckLogWindow = channel.unary_unary(
                '/LogQuery/CheckLogWindow',
                request_serializer=logquery__pb2.LogQueryRequest.SerializeToString,
                response_deserializer=logquery__pb2.LogQueryResponse.FromString,
                )


class LogQueryServicer(object):
    """The logquery service definition.
    """

    def CheckLogWindow(self, request, context):
        """Checks if timewindow exists in the logs.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LogQueryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckLogWindow': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckLogWindow,
                    request_deserializer=logquery__pb2.LogQueryRequest.FromString,
                    response_serializer=logquery__pb2.LogQueryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'LogQuery', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LogQuery(object):
    """The logquery service definition.
    """

    @staticmethod
    def CheckLogWindow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/LogQuery/CheckLogWindow',
            logquery__pb2.LogQueryRequest.SerializeToString,
            logquery__pb2.LogQueryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
